### ISSUE TITLE
1.0.1: tox based test suite is failing

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx-testing#21] opened 2020-10-01 23:31 UTC
I know that pytest is working (#15). but it is one issue with using pytest.
pytest requires sphinx-testing in own test suite.

Because I found tox.ini file I've been trying to use tox on testing and looks like it fails
It would be good to fix tox tests to npot have that loop in build dependencies.
```
[tkloczko@barrel sphinx-testing-1.0.1]$ tox --skip-missing-interpreters
GLOB sdist-make: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/setup.py
py26 create: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/py26
SKIPPED: InterpreterNotFound: python2.6
py27 create: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py34 create: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
sphinx06 create: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06
sphinx06 installdeps: nose, mock, flake8, Sphinx <= 0.6.9999
ERROR: invocation failed (exit code 1), logfile: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06/log/sphinx06-1.log
============================================================================================== log start ===============================================================================================
Collecting nose
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
Collecting mock
  Using cached https://files.pythonhosted.org/packages/cd/74/d72daf8dff5b6566db857cfd088907bb0355f5dd2914c4b3ef065c790735/mock-4.0.2-py3-none-any.whl
Collecting flake8
  Using cached https://files.pythonhosted.org/packages/6c/20/6326a9a0c6f0527612bae748c4c03df5cd69cf06dfb2cf59d85c6e165a6a/flake8-3.8.3-py2.py3-none-any.whl
Collecting Sphinx<=0.6.9999
  Using cached https://files.pythonhosted.org/packages/e2/3b/3766991dc30b590fd1246b291fc846b29b71b677d359da0845810816c48c/Sphinx-0.6.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qtpjnor2/Sphinx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qtpjnor2/Sphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qtpjnor2/Sphinx/pip-egg-info
         cwd: /tmp/pip-install-qtpjnor2/Sphinx/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qtpjnor2/Sphinx/setup.py", line 48
        print 'ERROR: Sphinx requires at least Python 2.4 to run.'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('ERROR: Sphinx requires at least Python 2.4 to run.')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

=============================================================================================== log end ================================================================================================
ERROR: could not install deps [nose, mock, flake8, Sphinx <= 0.6.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06/bin/python -m pip install nose mock flake8 'Sphinx <= 0.6.9999'", 1)
sphinx10 create: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10
sphinx10 installdeps: nose, mock, flake8, Sphinx <= 1.0.9999
ERROR: invocation failed (exit code 1), logfile: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10/log/sphinx10-1.log
============================================================================================== log start ===============================================================================================
Collecting nose
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
Collecting mock
  Using cached https://files.pythonhosted.org/packages/cd/74/d72daf8dff5b6566db857cfd088907bb0355f5dd2914c4b3ef065c790735/mock-4.0.2-py3-none-any.whl
Collecting flake8
  Using cached https://files.pythonhosted.org/packages/6c/20/6326a9a0c6f0527612bae748c4c03df5cd69cf06dfb2cf59d85c6e165a6a/flake8-3.8.3-py2.py3-none-any.whl
Collecting Sphinx<=1.0.9999
  Using cached https://files.pythonhosted.org/packages/af/15/7512fa421f3a78233753635d00f757103ffaa11699550692c633b11e44dd/Sphinx-1.0.8.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-72fe_4sy/Sphinx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-72fe_4sy/Sphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-72fe_4sy/Sphinx/pip-egg-info
         cwd: /tmp/pip-install-72fe_4sy/Sphinx/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-72fe_4sy/Sphinx/setup.py", line 50
        print 'ERROR: Sphinx requires at least Python 2.4 to run.'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('ERROR: Sphinx requires at least Python 2.4 to run.')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

=============================================================================================== log end ================================================================================================
ERROR: could not install deps [nose, mock, flake8, Sphinx <= 1.0.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10/bin/python -m pip install nose mock flake8 'Sphinx <= 1.0.9999'", 1)
sphinx11 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx11 installed: docutils==0.16,flake8==3.8.3,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,six==1.15.0,Sphinx==1.1.3,sphinx-testing==1.0.1
sphinx11 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx11 run-test: commands[0] | nosetests
.........................E.......E......
======================================================================
ERROR: test_TestApp (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/docutils/core.py", line 178, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 732, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 36, in test_TestApp
    app.build()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 194, in build_update
    self.build(to_build,
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 215, in build
    for docname in self.status_iterator(iterator, 'reading sources... ',
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 758, in read_doc
    pub.set_source(None, src_path.encode(fs_encoding))
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/docutils/core.py", line 182, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 732, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

======================================================================
ERROR: test_with_app (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/docutils/core.py", line 178, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 732, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 150, in test_with_app
    execute()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/src/sphinx_testing/util.py", line 171, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 141, in execute
    app.build()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 194, in build_update
    self.build(to_build,
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 215, in build
    for docname in self.status_iterator(iterator, 'reading sources... ',
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 758, in read_doc
    pub.set_source(None, src_path.encode(fs_encoding))
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/docutils/core.py", line 182, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/lib/python3.8/site-packages/sphinx/environment.py", line 732, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

----------------------------------------------------------------------
Ran 40 tests in 0.250s

FAILED (errors=2)
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx11/bin/nosetests (exited with code 1)
sphinx12 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx12 installed: docutils==0.16,flake8==3.8.3,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,six==1.15.0,Sphinx==1.2.3,sphinx-testing==1.0.1
sphinx12 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx12 run-test: commands[0] | nosetests
.........................E.......E......
======================================================================
ERROR: test_TestApp (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/docutils/core.py", line 178, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 597, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 36, in test_TestApp
    app.build()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 212, in build_update
    self.build(to_build,
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 233, in build
    for docname in self.status_iterator(iterator, 'reading sources... ',
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 478, in update_generator
    self.read_doc(docname, app=app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 626, in read_doc
    pub.set_source(None, src_path)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/docutils/core.py", line 182, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 597, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

======================================================================
ERROR: test_with_app (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/docutils/core.py", line 178, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 597, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 150, in test_with_app
    execute()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/src/sphinx_testing/util.py", line 171, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/tests/test_util.py", line 141, in execute
    app.build()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 212, in build_update
    self.build(to_build,
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 233, in build
    for docname in self.status_iterator(iterator, 'reading sources... ',
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 478, in update_generator
    self.read_doc(docname, app=app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 626, in read_doc
    pub.set_source(None, src_path)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/docutils/core.py", line 182, in set_source
    self.source = self.source_class(
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/lib/python3.8/site-packages/sphinx/environment.py", line 597, in __init__
    FileInput.__init__(self_, *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'handle_io_errors'

----------------------------------------------------------------------
Ran 40 tests in 0.249s

FAILED (errors=2)
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx12/bin/nosetests (exited with code 1)
sphinx13 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx13 installed: alabaster==0.7.12,Babel==2.8.0,docutils==0.16,flake8==3.8.3,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pytz==2020.1,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.3.6,sphinx-rtd-theme==0.5.0,sphinx-testing==1.0.1
sphinx13 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx13 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.569s

OK
sphinx13 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx14 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx14 installed: alabaster==0.7.12,Babel==2.8.0,docutils==0.16,flake8==3.8.3,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pytz==2020.1,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.4.9,sphinx-testing==1.0.1
sphinx14 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx14 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.588s

OK
sphinx14 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx15 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx15 installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,flake8==3.8.3,idna==2.10,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.5.6,sphinx-testing==1.0.1,urllib3==1.25.10
sphinx15 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx15 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.683s

OK
sphinx15 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx16 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx16 installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,flake8==3.8.3,idna==2.10,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.6.7,sphinx-testing==1.0.1,sphinxcontrib-serializinghtml==1.1.4,sphinxcontrib-websupport==1.2.4,urllib3==1.25.10
sphinx16 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx16 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.774s

OK
sphinx16 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx17 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx17 installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,flake8==3.8.3,idna==2.10,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,packaging==20.4,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pyparsing==2.4.7,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.7.9,sphinx-testing==1.0.1,sphinxcontrib-serializinghtml==1.1.4,sphinxcontrib-websupport==1.2.4,urllib3==1.25.10
sphinx17 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx17 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.795s

OK
sphinx17 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx18 inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx18 installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,flake8==3.8.3,idna==2.10,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,packaging==20.4,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pyparsing==2.4.7,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.8.5,sphinx-testing==1.0.1,sphinxcontrib-serializinghtml==1.1.4,sphinxcontrib-websupport==1.2.4,urllib3==1.25.10
sphinx18 run-test-pre: PYTHONHASHSEED='1897949937'
sphinx18 run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.828s

OK
sphinx18 run-test: commands[1] | flake8 setup.py src/ tests/
sphinx-dev inst-nodeps: /home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/.tmp/package/1/sphinx-testing-1.0.1.zip
sphinx-dev installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,flake8==3.8.3,idna==2.10,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.2,nose==1.3.7,packaging==20.4,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.7.1,pyparsing==2.4.7,pytz==2020.1,requests==2.24.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==3.3.0.dev20201002,sphinx-testing==1.0.1,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==1.0.3,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.4,urllib3==1.25.10
sphinx-dev run-test-pre: PYTHONHASHSEED='1897949937'
sphinx-dev run-test: commands[0] | nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.871s

OK
sphinx-dev run-test: commands[1] | flake8 setup.py src/ tests/
_______________________________________________________________________________________________ summary ________________________________________________________________________________________________
SKIPPED:  py26: InterpreterNotFound: python2.6
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py34: InterpreterNotFound: python3.4
ERROR:   sphinx06: could not install deps [nose, mock, flake8, Sphinx <= 0.6.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06/bin/python -m pip install nose mock flake8 'Sphinx <= 0.6.9999'", 1)
ERROR:   sphinx10: could not install deps [nose, mock, flake8, Sphinx <= 1.0.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10/bin/python -m pip install nose mock flake8 'Sphinx <= 1.0.9999'", 1)
ERROR:   sphinx11: commands failed
ERROR:   sphinx12: commands failed
  sphinx13: commands succeeded
  sphinx14: commands succeeded
  sphinx15: commands succeeded
  sphinx16: commands succeeded
  sphinx17: commands succeeded
  sphinx18: commands succeeded
  sphinx-dev: commands succeeded
```

**Comment by tk0miya** [comment] 2020-10-02 15:38
It's not a bug. Sphinx 1.2 and older are not working with python 3.8. It will be working fine if you run it under python2.7 or 3.4. And they have already been removed in the HEAD of this repository now.

**Comment by kloczek** [comment] 2020-10-02 22:14
I'm using python sphinx-3.2.1.
Do you know that python 2.x is already EOLed?
https://www.infoq.com/news/2019/09/python-2-end-of-life-approaching/#:~:text=After%20spreading%20the%20news%20at,)%20on%20January%201st%2C%202020.

**Comment by tk0miya** [comment] 2020-10-03 00:57
Of course, yes. Please let you see what versions of Sphinx failed tests. I guess you'd like to pass testcases for Sphinx 0.6-1.2. Is this right?

>ERROR:   sphinx06: could not install deps [nose, mock, flake8, Sphinx <= 0.6.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx06/bin/python -m pip install nose mock flake8 'Sphinx <= 0.6.9999'", 1)
ERROR:   sphinx10: could not install deps [nose, mock, flake8, Sphinx <= 1.0.9999]; v = InvocationError("/home/tkloczko/rpmbuild/BUILD/sphinx-testing-1.0.1/.tox/sphinx10/bin/python -m pip install nose mock flake8 'Sphinx <= 1.0.9999'", 1)
ERROR:   sphinx11: commands failed
ERROR:   sphinx12: commands failed

**Comment by kloczek** [comment] 2020-10-03 03:14
It does not make any sense.
Why tox is trying to use those executabl;es? and/or how to disable that and test everything only against sphinx installed in sytstem tree?

**Comment by tk0miya** [comment] 2020-10-03 08:13
tox always creates virtual environments and installs dependencies to them. So no ways to test against Sphinx installed in system tree.

FYI: this package is no longer maintained. So no proper way to test with recent Sphinx releases.

**Comment by tk0miya** [comment] 2020-11-08 12:38
>FYI: this package is no longer maintained. So no proper way to test with recent Sphinx releases.

Now we determined to archive this project. Closing.

**Closed as completed by tk0miya** 2020-11-08 12:38 UTC
